# Generated by Django 5.2.5 on 2025-10-29 10:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marshrut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marshrut_raqam', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NosozlikTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosozlik_turi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('monitoring', 'Monitoring'), ('texnik', 'Texnik'), ('jadval', 'Jadval')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EhtiyotQismlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehtiyotqism_nomi', models.CharField(max_length=255, unique=True)),
                ('nomenklatura_raqami', models.CharField(max_length=100)),
                ('birligi', models.CharField(choices=[('dona', 'Dona'), ('para', 'Para'), ('metr', 'Metr'), ('litr', 'Litr')], default='dona', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EhtiyotQismHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehtiyotqism_hist', to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='ElektroDepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_nomi', models.CharField(max_length=255)),
                ('qisqacha_nomi', models.CharField(max_length=50)),
                ('depo_rahbari', models.CharField(blank=True, max_length=255, null=True)),
                ('joylashuvi', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='depo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ehtiyotqismlari',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.elektrodepo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='home.elektrodepo'),
        ),
        migrations.CreateModel(
            name='HarakatTarkibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=100)),
                ('tarkib_raqami', models.CharField(blank=True, max_length=255, null=True)),
                ('ishga_tushgan_vaqti', models.BigIntegerField(help_text='yilda')),
                ('eksplutatsiya_vaqti', models.BigIntegerField(help_text='yilda')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarkiblar/')),
                ('holati', models.CharField(choices=[('Soz_holatda', 'Soz_holatda'), ('Texnik_korikda', 'Texnik_korikda'), ('Nosozlikda', 'Nosozlikda')], default='Soz_holatda', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarkiblar', to='home.elektrodepo')),
                ('pervious_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='home.harakattarkibi')),
            ],
        ),
        migrations.CreateModel(
            name='KunlikYurish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('kilometr', models.PositiveIntegerField(help_text='Yurilgan km')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarkib', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunlik_yurishlar', to='home.harakattarkibi')),
            ],
            options={
                'ordering': ['-sana', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NosozlikEhtiyotQism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='NosozlikEhtiyotQismStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='Nosozliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bartaraf_etilgan_nosozliklar', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Nosozlikda', 'Nosozlikda'), ('Soz_holatda', 'Soz_holatda')], default='Nosozlikda', editable=False, max_length=32)),
                ('aniqlangan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('bartarafqilingan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='nosozlik_aktlar/')),
                ('image', models.ImageField(blank=True, upload_to='nosozlik_images/')),
                ('yakunlash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, related_name='nosozliklar', through='home.NosozlikEhtiyotQism', to='home.ehtiyotqismlari')),
                ('tarkib', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosozliklar', to='home.harakattarkibi')),
                ('nosozliklar_haqida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosozliklar_main', to='home.nosozlikturi')),
            ],
        ),
        migrations.AddField(
            model_name='nosozlikehtiyotqism',
            name='nosozlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehtiyot_qism_aloqalari', to='home.nosozliklar'),
        ),
        migrations.CreateModel(
            name='NosozlikStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yakunlandi', 'Yakunlandi')], default='Jarayonda', max_length=20)),
                ('bartaraf_etilgan_nosozliklar', models.TextField(blank=True)),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='nosozlik_step_aktlar/')),
                ('bartaraf_qilingan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, through='home.NosozlikEhtiyotQismStep', to='home.ehtiyotqismlari')),
                ('nosozlik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='home.nosozliklar')),
                ('nosozliklar_haqida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosozlikla_step', to='home.nosozlikturi')),
            ],
        ),
        migrations.AddField(
            model_name='nosozlikehtiyotqismstep',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehtiyot_qismlar_step', to='home.nosozlikstep'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nosozlik', 'Nosozlik'), ('texnik_korik', 'Texnik ko‘rik'), ('ehtiyot_qism', 'Ehtiyot qism')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('nosozlik_turi', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('ehtiyot_qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari')),
                ('tarkib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.harakattarkibi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TamirTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamir_nomi', models.CharField(max_length=255)),
                ('tamirlash_davri', models.CharField(help_text='Masofa bo‘yicha: 5505 km', max_length=50)),
                ('tarkib_turi', models.CharField(blank=True, choices=[('Moskva(81-765,766,767)', 'Moskva(81-765,766,767)'), ('81-714,714.5,717,717.5,718,719 (Tisu)', '81-714,714.5,717,717.5,718,719 (Tisu)')], help_text='Tarkib turini tanlang', max_length=50, null=True)),
                ('tamirlanish_miqdori', models.PositiveIntegerField(blank=True, help_text='Vaqt soni: masalan, 4', null=True)),
                ('tamirlanish_vaqti', models.CharField(choices=[('soat', 'Soat'), ('kun', 'Kun'), ('oy', 'Oy')], help_text='Vaqt birligi: soat/kun/oy', max_length=10)),
                ('akt_check', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nosozlikstep',
            name='tamir_turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi'),
        ),
        migrations.CreateModel(
            name='TexnikKorik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Texnik_korikda', 'Texnik_korikda'), ('Soz_holatda', 'Soz_holatda')], default='Texnik_korikda', editable=False, max_length=32)),
                ('kamchiliklar_haqida', models.TextField(blank=True)),
                ('bartaraf_etilgan_kamchiliklar', models.TextField(blank=True)),
                ('kirgan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiqqan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='texnik_korik_aktlar/')),
                ('yakunlash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi')),
                ('tarkib', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koriklar', to='home.harakattarkibi')),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorikEhtiyotQism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari')),
                ('korik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorik')),
            ],
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='ehtiyot_qismlar',
            field=models.ManyToManyField(blank=True, through='home.TexnikKorikEhtiyotQism', to='home.ehtiyotqismlari'),
        ),
        migrations.CreateModel(
            name='TexnikKorikEhtiyotQismStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorikStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yakunlandi', 'Yakunlandi')], default='Jarayonda', max_length=20)),
                ('kamchiliklar_haqida', models.TextField(blank=True)),
                ('bartaraf_etilgan_kamchiliklar', models.TextField(blank=True)),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='akt/')),
                ('chiqqan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, through='home.TexnikKorikEhtiyotQismStep', to='home.ehtiyotqismlari')),
                ('korik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='home.texnikkorik')),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi')),
            ],
        ),
        migrations.AddField(
            model_name='texnikkorikehtiyotqismstep',
            name='korik_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorikstep'),
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagon_raqami', models.CharField(max_length=50)),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagonlar', to='home.harakattarkibi')),
            ],
        ),
        migrations.CreateModel(
            name='YilOy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField()),
                ('oy', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('yil', 'oy')},
            },
        ),
        migrations.CreateModel(
            name='TexnikKorikJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(help_text='Texnik ko‘rik belgilangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('marshrut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='korik_jadvallari', to='home.marshrut')),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='korik_jadvallari', to='home.tamirturi')),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korik_jadvallari', to='home.harakattarkibi')),
            ],
            options={
                'verbose_name': 'Texnik ko‘rik jadvali',
                'verbose_name_plural': 'Texnik ko‘rik jadvallari',
                'ordering': ['-sana'],
                'unique_together': {('tarkib', 'sana')},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='home.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
