# Generated by Django 5.2.5 on 2025-09-03 11:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('monitoring', 'Monitoring'), ('texnik', 'Texnik')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EhtiyotQismlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehtiyotqism_nomi', models.CharField(max_length=255, unique=True)),
                ('nomenklatura_raqami', models.CharField(max_length=100)),
                ('birligi', models.CharField(choices=[('dona', 'Dona'), ('para', 'Para'), ('metr', 'Metr'), ('litr', 'Litr')], default='dona', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElektroDepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_nomi', models.CharField(max_length=255)),
                ('qisqacha_nomi', models.CharField(max_length=50)),
                ('joylashuvi', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='depo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarakatTarkibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruhi', models.CharField(max_length=100)),
                ('turi', models.CharField(max_length=100)),
                ('tarkib_raqami', models.CharField(max_length=100, unique=True)),
                ('ishga_tushgan_vaqti', models.DateField()),
                ('eksplutatsiya_vaqti', models.IntegerField(help_text='km da')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarkiblar/')),
                ('holati', models.CharField(choices=[('Sof holatda', 'Sof holatda'), ("Texnik ko'rikda", "Texnik ko'rikda"), ('Nosozlikda', 'Nosozlikda')], default='Sof holatda', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarkiblar', to='home.elektrodepo')),
            ],
        ),
        migrations.CreateModel(
            name='NosozlikEhtiyotQism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='Nosozliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosozliklar', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOSOZLIKDA', 'Nosozlikda'), ('SOF HOLATDA', 'Sof holatda')], default='NOSOZLIKDA', max_length=32)),
                ('aniqlangan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('bartarafqilingan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, help_text='Bartaraf etilish jarayonida bajarilgan ishlar')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, related_name='nosozliklar', through='home.NosozlikEhtiyotQism', to='home.ehtiyotqismlari')),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nosozliklar', to='home.harakattarkibi')),
            ],
        ),
        migrations.AddField(
            model_name='nosozlikehtiyotqism',
            name='nosozlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nosozliklar'),
        ),
        migrations.CreateModel(
            name='TamirTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamir_nomi', models.CharField(max_length=255)),
                ('tamirlash_davri', models.CharField(help_text='Masofa bo‘yicha: 5505 ± 10 km', max_length=50)),
                ('tamirlanish_vaqti', models.CharField(default='1 soat', help_text='Masalan: 1 soat, 6 oy, 30 daqiqa', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kamchiliklar', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[("TEXNIK KO'RIKDA", "Texnik ko'rikda"), ('SOF HOLATDA', 'Sof holatda')], default="TEXNIK KO'RIKDA", max_length=32)),
                ('kirgan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiqqan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kirgan_foydalanuvchilar', to=settings.AUTH_USER_MODEL)),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koriklar', to='home.tamirturi')),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koriklar', to='home.harakattarkibi')),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorikEhtiyotQism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari')),
                ('korik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorik')),
            ],
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='ehtiyot_qismlar',
            field=models.ManyToManyField(blank=True, related_name='koriklar', through='home.TexnikKorikEhtiyotQism', to='home.ehtiyotqismlari'),
        ),
    ]
