# Generated by Django 5.2.5 on 2025-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='eksplutatsiya_vaqti',
            field=models.IntegerField(help_text='yilda'),
        ),
        migrations.AlterField(
            model_name='harakattarkibi',
            name='ishga_tushgan_vaqti',
            field=models.IntegerField(help_text='yilda'),
        ),
    ]
