# Generated by Django 5.2.5 on 2025-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YilOy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField()),
                ('oy', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('yil', 'oy')},
            },
        ),
    ]
