# Generated by Django 5.2.5 on 2025-08-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nossozliklar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='user',
        ),
    ]
