# Generated by Django 5.2.5 on 2025-10-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NosozlikNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosozlik_turi', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('first_occurrence', models.DateTimeField(blank=True, null=True)),
                ('last_occurrence', models.DateTimeField(auto_now_add=True)),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.harakattarkibi')),
            ],
        ),
    ]
