# Generated by Django 5.2.5 on 2025-09-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozliklar',
            name='status',
            field=models.CharField(choices=[('Nosozlikda', 'Nosozlikda'), ('Sof holatda', 'Sof holatda')], default='Nosozlikda', max_length=32),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='status',
            field=models.CharField(choices=[("Texnik ko'rikda", "Texnik ko'rikda"), ('Sof holatda', 'Sof holatda')], default="Texnik ko'rikda", max_length=32),
        ),
    ]
