# Generated by Django 5.2.5 on 2025-08-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_nossozliklar_user_remove_texnikkorik_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nossozliklar',
            new_name='Nosozliklar',
        ),
    ]
