# Generated by Django 5.2.5 on 2025-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_harakattarkibi_eksplutatsiya_vaqti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='eksplutatsiya_vaqti',
            field=models.CharField(help_text='yilda'),
        ),
        migrations.AlterField(
            model_name='harakattarkibi',
            name='ishga_tushgan_vaqti',
            field=models.CharField(help_text='yilda'),
        ),
    ]
