# Generated by Django 5.2.5 on 2025-09-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_nosozliklar_status_alter_texnikkorik_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosozliklar',
            name='akt_file',
            field=models.FileField(blank=True, null=True, upload_to='nosozlik_aktlar/'),
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='akt_file',
            field=models.FileField(blank=True, null=True, upload_to='korik_aktlar/'),
        ),
        migrations.AlterField(
            model_name='harakattarkibi',
            name='holati',
            field=models.CharField(choices=[('Soz holatda', 'Soz holatda'), ("Texnik ko'rikda", "Texnik ko'rikda"), ('Nosozlikda', 'Nosozlikda')], default='Soz holatda', max_length=100),
        ),
        migrations.AlterField(
            model_name='nosozliklar',
            name='status',
            field=models.CharField(choices=[('Nosozlikda', 'Nosozlikda'), ('Soz holatda', 'Soz holatda')], default='Nosozlikda', max_length=32),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='status',
            field=models.CharField(choices=[("Texnik ko'rikda", "Texnik ko'rikda"), ('Soz holatda', 'Soz holatda')], default="Texnik ko'rikda", max_length=32),
        ),
        migrations.CreateModel(
            name='NosozlikImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nosozlik_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nosozlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.nosozliklar')),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorikImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='korik_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('korik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.texnikkorik')),
            ],
        ),
    ]
