# Generated by Django 5.2.5 on 2025-10-28 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_yiloy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='ehtiyot_qism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_occurrence',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='nosozlik_turi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='tarkib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.harakattarkibi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nosozlik', 'Nosozlik'), ('texnik_korik', 'Texnik ko‘rik'), ('ehtiyot_qism', 'Ehtiyot qism')], default='nosozlik', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NosozlikNotification',
        ),
    ]
