# Generated by Django 5.2.5 on 2025-10-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nosozliknotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozliknotification',
            name='last_occurrence',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
