# Generated by Django 5.2.5 on 2025-10-15 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_nosozliknotification_last_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexnikKorikJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(help_text='Texnik ko‘rik belgilangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tamir_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korik_jadvallari', to='home.tamirturi')),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korik_jadvallari', to='home.harakattarkibi')),
            ],
            options={
                'verbose_name': 'Texnik ko‘rik jadvali',
                'verbose_name_plural': 'Texnik ko‘rik jadvallari',
                'ordering': ['-sana'],
                'unique_together': {('tarkib', 'sana')},
            },
        ),
    ]
