# Generated by Django 5.2.5 on 2025-09-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nosozliklar_akt_file_texnikkorik_akt_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texnikkorikimage',
            name='korik',
        ),
        migrations.AddField(
            model_name='nosozliklar',
            name='image',
            field=models.ImageField(blank=True, upload_to='nosozlik_images/'),
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='korik_images/'),
        ),
        migrations.DeleteModel(
            name='NosozlikImage',
        ),
        migrations.DeleteModel(
            name='TexnikKorikImage',
        ),
    ]
