# Generated by Django 5.2.5 on 2025-10-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification_count_notification_ehtiyot_qism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nosozlik', 'Nosozlik'), ('texnik_korik', 'Texnik ko‘rik'), ('ehtiyot_qism', 'Ehtiyot qism')], max_length=50),
        ),
    ]
