# Generated by Django 5.2.5 on 2025-10-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_harakattarkibi_eksplutatsiya_vaqti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehtiyotqismlari',
            name='birligi',
            field=models.CharField(choices=[('dona', 'Dona'), ('para', 'Para'), ('metr', 'Metr'), ('litr', 'Litr'), ('kg', 'Kg'), ('banka', 'Banka'), ('metr_kv', 'Metr_kv'), ('metr_kub', 'Metr_kub'), ("to'plam", "To'plam"), ('quti', 'Quti'), ('rulon', 'Rulon'), ('k-t', 'K-t')], default='dona', max_length=50),
        ),
        migrations.AlterField(
            model_name='ehtiyotqismlari',
            name='ehtiyotqism_nomi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ehtiyotqismlari',
            name='nomenklatura_raqami',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
