# Generated by Django 5.2.5 on 2025-09-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_texnikkorikimage_korik_nosozliklar_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nosozliklar',
            old_name='comment',
            new_name='bartaraf_etilgan_nosozliklar',
        ),
        migrations.RenameField(
            model_name='nosozliklar',
            old_name='nosozliklar',
            new_name='nosozliklar_haqida',
        ),
        migrations.RenameField(
            model_name='texnikkorik',
            old_name='comment',
            new_name='Bartaraf_etilgan_kamchiliklar',
        ),
        migrations.RenameField(
            model_name='texnikkorik',
            old_name='kamchiliklar',
            new_name='kamchiliklar_haqida',
        ),
    ]
