# Generated by Django 5.2.5 on 2025-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_nosozliklar_created_by_texnikkorik_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehtiyotqismlari',
            name='ehtiyotqism_nomi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
