# Generated by Django 5.2.5 on 2025-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_texnikkorikjadval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehtiyotqismlari',
            name='jami_miqdor',
            field=models.FloatField(default=0),
        ),
    ]
