# Generated by Django 5.2.5 on 2025-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ehtiyotqismlari_ehtiyotqism_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='holati',
            field=models.CharField(choices=[('liniyada', 'Liniyada'), ("texnik ko'rikda", "Texnik ko'rikda"), ('faoliyati tugagan', 'Faoliyati tugagan')], default='liniyada', max_length=100),
        ),
    ]
