# Generated by Django 5.2.5 on 2025-10-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ehtiyotqismlari_jami_miqdor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehtiyotqismlari',
            name='jami_miqdor',
        ),
    ]
