# Generated by Django 5.2.5 on 2025-09-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_comment_nosozliklar_bartaraf_etilgan_nosozliklar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texnikkorik',
            old_name='Bartaraf_etilgan_kamchiliklar',
            new_name='bartaraf_etilgan_kamchiliklar',
        ),
    ]
