# Generated by Django 5.2.5 on 2025-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_bartaraf_etilgan_kamchiliklar_texnikkorik_bartaraf_etilgan_kamchiliklar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosozliklar',
            name='dastlabki_holat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
