# Generated by Django 5.2.5 on 2025-10-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosozliknotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
