# Generated by Django 5.2.5 on 2025-09-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nosozliklar_dastlabki_holat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nosozliklar',
            name='dastlabki_holat',
        ),
    ]
