# Generated by Django 5.2.5 on 2025-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ehtiyotqismlari_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehtiyotqismlari',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='elektrodepo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='harakattarkibi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nosozliklar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tamirturi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
