# Generated by Django 5.2.5 on 2025-09-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_nosozliklar_dastlabki_holat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozliklar',
            name='status',
            field=models.CharField(choices=[('Nosozlikda', 'Nosozlikda'), ('Soz holatda', 'Soz holatda')], default='Nosozlikda', editable=False, max_length=32),
        ),
    ]
