# Generated by Django 5.2.5 on 2025-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_ehtiyotqismlari_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='holati',
            field=models.CharField(choices=[('Liniyada', 'liniyada'), ("Texnik ko'rikda", "texnik ko'rikda"), ('Faoliyati tugagan', 'faoliyati tugagan')], default='liniyada', max_length=100),
        ),
    ]
