# Generated by Django 5.2.5 on 2025-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_harakattarkibi_holati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='holati',
            field=models.CharField(choices=[('Liniyada', 'Liniyada'), ("Texnik ko'rikda", "Texnik ko'rikda"), ('Faoliyati tugagan', 'Faoliyati tugagan')], default='Liniyada', max_length=100),
        ),
    ]
