# Generated by Django 5.2.5 on 2025-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_nosozliklar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texnikkorik',
            name='status',
            field=models.CharField(choices=[("Texnik ko'rikda", "Texnik ko'rikda"), ('Soz holatda', 'Soz holatda')], default="Texnik ko'rikda", editable=False, max_length=32),
        ),
    ]
