# Generated by Django 5.2.5 on 2025-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_texnikkorik_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='holati',
            field=models.CharField(choices=[('Soz_holatda', 'Soz_holatda'), ('Texnik_korikda', 'Texnik_korikda'), ('Nosozlikda', 'Nosozlikda')], default='Soz_holatda', max_length=100),
        ),
        migrations.AlterField(
            model_name='nosozliklar',
            name='status',
            field=models.CharField(choices=[('Nosozlikda', 'Nosozlikda'), ('Soz_holatda', 'Soz_holatda')], default='Nosozlikda', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='status',
            field=models.CharField(choices=[('Texnik_korikda', 'Texnik_korikda'), ('Soz_holatda', 'Soz_holatda')], default='Texnik_korikda', editable=False, max_length=32),
        ),
    ]
