# Generated by Django 5.2.5 on 2025-09-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_harakattarkibi_holati_alter_nosozliklar_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='eksplutatsiya_vaqti',
            field=models.BigIntegerField(help_text='km da'),
        ),
    ]
