# Generated by Django 5.2.5 on 2025-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_harakattarkibi_eksplutatsiya_vaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosozliklar',
            name='yakunlash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='yakunlash',
            field=models.BooleanField(default=False),
        ),
    ]
