# Generated by Django 5.2.5 on 2025-09-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_nosozliklar_yakunlash_texnikkorik_yakunlash'),
    ]

    operations = [
        migrations.AddField(
            model_name='texnikkorik',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.texnikkorik'),
        ),
    ]
