# Generated by Django 5.2.5 on 2025-09-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_texnikkorik_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texnikkorik',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='bartaraf_etilgan_kamchiliklar',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='image',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='kamchiliklar_haqida',
        ),
        migrations.RemoveField(
            model_name='texnikkorik',
            name='parent',
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='ehtiyot_qismlar',
            field=models.ManyToManyField(blank=True, through='home.TexnikKorikEhtiyotQism', to='home.ehtiyotqismlari'),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='tamir_turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi'),
        ),
        migrations.CreateModel(
            name='TexnikKorikEhtiyotQismStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='TexnikKorikStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kamchiliklar_haqida', models.TextField(blank=True)),
                ('bartaraf_etilgan_kamchiliklar', models.TextField(blank=True)),
                ('chiqqan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, through='home.TexnikKorikEhtiyotQismStep', to='home.ehtiyotqismlari')),
                ('korik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.texnikkorik')),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi')),
            ],
        ),
        migrations.AddField(
            model_name='texnikkorikehtiyotqismstep',
            name='korik_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorikstep'),
        ),
    ]
