# Generated by Django 5.2.5 on 2025-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_texnikkorik_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texnikkorik',
            name='bartaraf_etilgan_kamchiliklar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='texnikkorik',
            name='kamchiliklar_haqida',
            field=models.TextField(blank=True),
        ),
    ]
