# Generated by Django 5.2.5 on 2025-09-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_texnikkorik_bartaraf_etilgan_kamchiliklar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texnikkorik',
            name='akt_file',
        ),
        migrations.AddField(
            model_name='texnikkorikstep',
            name='akt_file',
            field=models.FileField(blank=True, null=True, upload_to='akt/'),
        ),
    ]
