# Generated by Django 5.2.5 on 2025-09-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_texnikkorik_akt_file_texnikkorikstep_akt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='texnikkorikstep',
            name='status',
            field=models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yakunlandi', 'Yakunlandi')], default='Jarayonda', max_length=20),
        ),
    ]
