# Generated by Django 5.2.5 on 2025-09-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_texnikkorikstep_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nosozliklar',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='nosozliklar',
            name='approved_at',
        ),
        migrations.CreateModel(
            name='NosozlikEhtiyotQismStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ehtiyotqismlari')),
            ],
        ),
        migrations.CreateModel(
            name='NosozlikStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yakunlandi', 'Yakunlandi')], default='Jarayonda', max_length=20)),
                ('nosozliklar_haqida', models.TextField(blank=True)),
                ('bartaraf_etilgan_nosozliklar', models.TextField(blank=True)),
                ('akt_file', models.FileField(blank=True, null=True, upload_to='nosozlik_step_aktlar/')),
                ('bartaraf_qilingan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qismlar', models.ManyToManyField(blank=True, through='home.NosozlikEhtiyotQismStep', to='home.ehtiyotqismlari')),
                ('nosozlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.nosozliklar')),
                ('tamir_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tamirturi')),
            ],
        ),
        migrations.AddField(
            model_name='nosozlikehtiyotqismstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehtiyot_qismlar_step', to='home.nosozlikstep'),
        ),
    ]
