# Generated by Django 5.2.5 on 2025-09-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_nosozliklar_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozlikehtiyotqism',
            name='nosozlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehtiyot_qism_aloqalari', to='home.nosozliklar'),
        ),
    ]
