# Generated by Django 5.2.5 on 2025-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_nosozlikehtiyotqism_nosozlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='texnikkorik',
            name='akt_file',
            field=models.FileField(blank=True, null=True, upload_to='texnik_korik_aktlar/'),
        ),
    ]
