# Generated by Django 5.2.5 on 2025-09-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_texnikkorik_akt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamirturi',
            name='tamirlanish_vaqti',
            field=models.CharField(choices=[('soat', 'soat'), ('kun', 'kun'), ('oy', 'oy')], max_length=50),
        ),
    ]
