# Generated by Django 5.2.5 on 2025-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_tamirturi_tamirlanish_vaqti'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamirturi',
            name='tamirlanish_miqdori',
            field=models.PositiveIntegerField(blank=True, help_text='Vaqt soni: masalan, 4', null=True),
        ),
        migrations.AlterField(
            model_name='tamirturi',
            name='tamirlanish_vaqti',
            field=models.CharField(choices=[('soat', 'Soat'), ('kun', 'Kun'), ('oy', 'Oy')], help_text='Vaqt birligi: soat/kun/oy', max_length=10),
        ),
    ]
