# Generated by Django 5.2.5 on 2025-09-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tamirturi_tamirlanish_miqdori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='home.elektrodepo'),
        ),
    ]
