# Generated by Django 5.2.5 on 2025-09-16 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_customuser_depo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunlikYurish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('kilometr', models.PositiveIntegerField(help_text='Yurilgan km')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunlik_yurishlar', to='home.harakattarkibi')),
            ],
            options={
                'ordering': ['-sana', '-id'],
            },
        ),
    ]
