# Generated by Django 5.2.5 on 2025-09-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_kunlikyurish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarkiblar', to='home.elektrodepo'),
        ),
        migrations.AlterField(
            model_name='kunlikyurish',
            name='tarkib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunlik_yurishlar', to='home.harakattarkibi'),
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqism',
            name='ehtiyot_qism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari'),
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqism',
            name='nosozlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehtiyot_qism_aloqalari', to='home.nosozliklar'),
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqismstep',
            name='ehtiyot_qism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari'),
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqismstep',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehtiyot_qismlar_step', to='home.nosozlikstep'),
        ),
        migrations.AlterField(
            model_name='nosozliklar',
            name='tarkib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosozliklar', to='home.harakattarkibi'),
        ),
        migrations.AlterField(
            model_name='nosozlikstep',
            name='nosozlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='home.nosozliklar'),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='tarkib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koriklar', to='home.harakattarkibi'),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqism',
            name='ehtiyot_qism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari'),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqism',
            name='korik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.texnikkorik'),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqismstep',
            name='ehtiyot_qism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ehtiyotqismlari'),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqismstep',
            name='korik_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.texnikkorikstep'),
        ),
        migrations.AlterField(
            model_name='texnikkorikstep',
            name='korik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='home.texnikkorik'),
        ),
    ]
