# Generated by Django 5.2.5 on 2025-09-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_harakattarkibi_depo_alter_kunlikyurish_tarkib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harakattarkibi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='harakattarkibi',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='home.harakattarkibi'),
        ),
        migrations.AlterField(
            model_name='harakattarkibi',
            name='tarkib_raqami',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagon_raqami', models.CharField(max_length=50)),
                ('model_nomi', models.CharField(blank=True, max_length=100, null=True)),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagonlar', to='home.harakattarkibi')),
            ],
        ),
    ]
