# Generated by Django 5.2.5 on 2025-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_harakattarkibi_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harakattarkibi',
            name='tarkib_raqami',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
