# Generated by Django 5.2.5 on 2025-09-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_harakattarkibi_tarkib_raqami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagon',
            name='model_nomi',
        ),
    ]
