# Generated by Django 5.2.5 on 2025-09-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_vagon_model_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozliklar',
            name='tarkib',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosozliklar', to='home.harakattarkibi'),
        ),
        migrations.AlterField(
            model_name='texnikkorik',
            name='tarkib',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koriklar', to='home.harakattarkibi'),
        ),
    ]
