# Generated by Django 5.2.5 on 2025-09-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_nosozliklar_tarkib_alter_texnikkorik_tarkib'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehtiyotqismlari',
            name='miqdori',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('monitoring', 'Monitoring'), ('texnik', 'Texnik'), ('skladchi', 'Skladchi')], max_length=20),
        ),
    ]
