# Generated by Django 5.2.5 on 2025-09-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ehtiyotqismlari_miqdori_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehtiyotqismlari',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.elektrodepo'),
        ),
    ]
