# Generated by Django 5.2.5 on 2025-09-24 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_ehtiyotqismlari_depo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehtiyotqismlari',
            name='miqdori',
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqism',
            name='miqdor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='nosozlikehtiyotqismstep',
            name='miqdor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqism',
            name='miqdor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqismstep',
            name='miqdor',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='EhtiyotQismHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ehtiyot_qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehtiyotqism_hist', to='home.ehtiyotqismlari')),
            ],
        ),
    ]
