# Generated by Django 5.2.5 on 2025-10-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_ehtiyotqismlari_miqdori_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harakattarkibi',
            old_name='previous_version',
            new_name='pervious_version',
        ),
    ]
