# Generated by Django 5.2.5 on 2025-10-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_previous_version_harakattarkibi_pervious_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texnikkorikehtiyotqism',
            name='korik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorik'),
        ),
        migrations.AlterField(
            model_name='texnikkorikehtiyotqismstep',
            name='korik_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.texnikkorikstep'),
        ),
    ]
