# Generated by Django 5.2.5 on 2025-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_texnikkorikehtiyotqism_korik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosozliklar',
            name='bartaraf_etilgan_nosozliklar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nosozlikstep',
            name='nosozliklar_haqida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
